# Cfg file for Env
world:
  type: 'Real'
  robot: 'sawyer'
data_dir: 'data'
# Simulation parameters
sim_params:
  time_step: 0.001 #0.004166  # 1./240.
  steps_per_action: 20 # policy to sim update ratio
  MAX_STEPS: 500
real_params: 
  nuc_hostname: "c3po-ctrl.stanford.edu" # Hostname for the NUC for real robot control. 
!include table_and_bin.yaml
!include sawyer.yaml
# Robots are specified by types and urdf locations
# also may include intial setup like poses and orientations

controller:
  selected_type: 'JointImpedance' # Choose between 'EEImpedance', 'JointVelocity'
  Real:
    EEImpedance:
      kp: [80.0, 80.0, 80.0, 10., 10., 10.] #70 #50 #200 #75 #200 # P Gain for Impedance Control
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1] 
      input_max: [1, 1, 1, 1, 1, 1]
      input_min: [-1, -1, -1, -1, -1, -1]
      output_max: [0.05, 0.05, 0.05, 1.57, 1.57, 1.57]
      output_min: [-0.05, -0.05, -0.05, -1.57, -1.57, -1.57]    
    JointVelocity: 
      kv: 8.0 #0.5
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0 #1.0
      output_min: -1.0 #-1.0
    JointImpedance: 
      kp: 100
      damping: 1.0
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    JointTorque: 
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    EEPosture:
      kp: 200 #70 #50 #200 #75 #200 # P Gain for Impedance Control
      damping: 0.8 #1 #0.5 #1 #0.5 # Damping factor [0,1] 
      posture_gain: 0.7
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
  interpolator:
    type: 'None'
    order: 1