# Cfg file for Env
world:
  type: 'Real'
  robot: 'sawyer'
data_dir: 'data'
# Simulation parameters
sim_params:
  time_step: 0.001 #0.004166  # 1./240.
  steps_per_action: 20 # policy to sim update ratio
  MAX_STEPS: 500
real_params: 
  nuc_hostname: "localhost" # Hostname for the NUC for real robot control. 

# redis: 
#   host: c3po-ctrl.stanford.edu
#   port: 6379
#   password: "tarsbendervisiongoddardr2d2sawyerbb8"
   
redis: 
  host: localhost
  port: 6379

!include table_and_bin.yaml
# Robots are specified by types and urdf locations
# also may include intial setup like poses and orientations

controller:
  selected_type: 'EEPosture' # Choose between 'EEImpedance', 'JointVelocity'
  Real:
    EEImpedance:
      kp: [40.0, 40.0, 40.0, 10., 10., 10.] #70 #50 #200 #75 #200 # P Gain for Impedance Control
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1] 
      input_max: [1, 1, 1, 1, 1, 1]
      input_min: [-1, -1, -1, -1, -1, -1]
      output_max: [1, 1, 1, 1, 1, 1]
      output_min: [-1, -1, -1, -1, -1, -1]
    JointVelocity: 
      kv: 8.0 #0.5
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0 #1.0
      output_min: -1.0 #-1.0
    JointImpedance: 
      kp: 100
      damping: 1.0
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    JointTorque: 
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    EEPosture:
      kp: [40.0, 40.0, 40.0, 10.0, 10.0, 10.0] #70 #50 #200 #75 #200 # P Gain for Impedance Control
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1] 
      posture_gain: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] #[25.0, 25.0, 25.0, 20.0, 15.0, 15.0, 15.0] #[70.0, 70.0, 70.0, 60.0, 50.0, 50.0, 50.0]
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
  interpolator:
    type: 'linear'
    order: 1

# Cfg file for sawyer arm
sawyer:
  arm:
    path:
      'robot/rethink/sawyer_description/urdf/sawyer_arm_ctrl.urdf'
    pose:
      [0, 0, 0]
    orn:
      [0, 0, 0]
    is_static:
      True
  base: 
    path:
      'robot/rethink/sawyer_description/urdf/sawyer_base.urdf'
    pose:
      [0, 0, .01]
    orn:
      [0, 0, 0]
    is_static:
      True
  neutral_joint_angles:
    [0.00, -1.18, 0.00, 2.18, 0.00, 0.57, 1.5708]
  limb_joint_names: [
  'right_j0',
  'right_j1',
  'right_j2',
  'right_j3',
  'right_j4',
  'right_j5',
  'right_j6',
  ]
  # Height of the limb (installed on the base) from the ground, for computing IK.
  limb_height: 0.9
  # Link name of the end effector, for computing IK.
  end_effector_name: 'right_hand'
  # Joint name of the left finger of the gripper.
  l_finger_name: 'r_gripper_l_finger'
  # Joint name of the right finger of the gripper.
  r_finger_name: 'r_gripper_r_finger'
  # Link name of the left finger tip of the gripper.
  l_finger_tip_name: 'r_gripper_l_finger_tip'
  # Link name of the right finger tip of the gripper.
  r_finger_tip_name: 'r_gripper_r_finger_tip'

  # Default maximum joint velocity ratio, chosen from (0, 1].
  # Set it to 1.0 for data collection, 0.3 for demo.
  limb_max_velocity_ratio: 0.01

  # Threshold (in rads) for each joint for position control.
  limb_position_threshold: 0.008726640

  # Threshold (in rads) for each joint for position control.
  limb_velocity_threshold: 0.75

  # Step size of a gripper trajectory.
  end_effector_step: 0.02