# Cfg file for  Demo control environment 
world:
  type: 'Bullet' #'Bullet'
  robot: 'sawyer' #'panda'
data_dir: 'data'
# Simulation parameters
sim_params:
  time_step: 0.004166 #0.002 #0.004166  # 1./240.
  control_freq: 200 #4000 #5 #20
  steps_per_action: 1 #6 #1 #5 # policy to sim update ratio

  MAX_STEPS: 100000

!include ../../cfg/sawyer.yaml
!include ../../cfg/panda.yaml
!include ../../cfg/table_and_bin.yaml
scene_objects:
  'None'
goal_position:
  lower:
    [0.3, -0.2, 0.0]  # CHANGED
  upper:
    [0.5, 0.5, 0.2]   # CHANGED

sensor:
  camera:
    name:
        'camera'
    image:
      height: 224
      width: 224
    extrinsics:
        eye_position:
          [0.6, 0.0, 1.0]
        target_position:
          [0.6, 0., 0]
        up_vector:
          [1., 0., 1.]
    intrinsics:
        image_height: 1080
        image_width: 1920
        fov: 60
        near_plane: 0.02
        far_plane: 100
    # Parameters for randomization
    random:
      randomize: False
      extrinsics:
        eye_position:
          lower:
            [0.6, 0., 1.75]
          upper:
            [0.6, 0., 1.75]
        target_position:
          lower:
            [0.6, 0., 0]
          upper:
            [0.6, 0., 0]
      intrinsics:
        fov:
          lower: 50
          upper: 80
        near_plane:
          lower: 0.01
          upper: 0.05
        far_plane:
          lower: 10
          upper: 150

controller:
  selected_type: 'EEImpedance' # Choose between 'EEImpedance', 'JointVelocity'
  EEImpedance:
    kp: 50 #70 #50 #200 #75 #200 # P Gain for Impedance Control
    damping: .8 #1 #0.5 #1 #0.5 # Damping factor [0,1] 
    input_max: 1.0
    input_min: -1.0
    output_max: 1.0
    output_min: -1.0
  JointVelocity: 
    kv: 8.0 #0.5
    input_max: 1.0
    input_min: -1.0
    output_max: 1.0 #1.0
    output_min: -1.0 #-1.0
  JointImpedance: 
    kp: 100
    damping: 1.0
    input_max: 1.0
    input_min: -1.0
    output_max: 1.0
    output_min: -1.0
  JointTorque: 
    input_max: 1.0
    input_min: -1.0
    output_max: 1.0
    output_min: -1.0

object: 
  'None'
  # object_dict:
  #   # To add objects via arenas, list them directly using
  #   # key object_%i,
  #   object_0:
  #     name: '013_apple'
  #     path:
  #       'objects/ycb/013_apple/google_16k/textured.urdf'
  #     pose: [[1.5, 0, 0], [0,0,0]]
  #     is_static: True
  #     default_position: [0.7, 0.1, 0.03] #z  = 0.1
  #   object_1:
  #     name: '006_mustard_bottle'
  #     path:
  #       'objects/ycb/006_mustard_bottle/google_16k/textured.urdf'
  #     pose: [[0, 0, 0], [0, 0, 0]]
  #     is_static: False
  #     default_position: [0.2, 0.1, 0.03]

  # random:
  #   randomize: True
  #   position:
  #     lower:
  #       [0.3, -0.2, 0.1]
  #     upper:
  #       [0.7, 0.2, 0.1]

# Perception and Learning
env:
  observation_space:
    low:
      [-2.0, -2.0, -2.0]
    high:
      [2.0, 2.0, 2.0]
  action_space:
    low: [-0.2, -0.2, -0.2]
    high: [0.2, 0.2, 0.2]

learning_parms:
  hyperparameters:
  learning_rate:


vision_params:
  segmentation:
