# Teleop Environment Config
world:
  type: 'Bullet'
  robot: 'panda'
data_dir: '../../data'
# Simulation parameters
sim_params:
  time_step: 0.001 #0.004166  # 1./240.
  steps_per_action: 20 # policy to sim update ratio
  MAX_STEPS: 500

# Robots are specified by types and urdf locations
# also may include intial setup like poses and orientations
!include /vision2/u/rohunk/perls2/cfg/sawyer.yaml
!include /vision2/u/rohunk/perls2/cfg/panda.yaml
!include /vision2/u/rohunk/perls2/cfg/table_and_bin.yaml

sensor:
  camera:
    name:
        'camera'
    image:
      height: 224
      width: 224
    extrinsics:
        eye_position:
          [0.6, 0.0, 1.0]
        target_position:
          [0.6, 0., 0]
        up_vector:
          [1., 0., 1.]
    intrinsics:
        image_height: 1080
        image_width: 1920
        fov: 60
        near_plane: 0.02
        far_plane: 100
    # Parameters for randomization
    random:
      randomize: False
      extrinsics:
        eye_position:
          lower:
            [0.6, 0., 1.75]
          upper:
            [0.6, 0., 1.75]
        target_position:
          lower:
            [0.6, 0., 0]
          upper:
            [0.6, 0., 0]
      intrinsics:
        fov:
          lower: 50
          upper: 80
        near_plane:
          lower: 0.01
          upper: 0.05
        far_plane:
          lower: 10
          upper: 150